version: "3.9"

services:
  web:
    image: nginx:1.21
    working_dir: /www/app
    ports:
      -   "8111:80"
    volumes:
      -   ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      -   .:/www
    links:
      -   fpm
    command: nginx -g 'daemon off;'
  fpm:
    build: ./docker/fpm/
    working_dir: /www/app
    ports:
      -   "8112:9000"
    volumes:
      -   .:/www
